"""empty message

Revision ID: 482329800ac5
Revises: d0e376c69925
Create Date: 2020-03-05 08:17:22.493549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482329800ac5'
down_revision = 'd0e376c69925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem', sa.Column('poet', sa.String(), nullable=True))
    op.create_index(op.f('ix_poem_poet'), 'poem', ['poet'], unique=False)
    op.create_index(op.f('ix_poem_seed'), 'poem', ['seed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poem_seed'), table_name='poem')
    op.drop_index(op.f('ix_poem_poet'), table_name='poem')
    op.drop_column('poem', 'poet')
    # ### end Alembic commands ###
