"""users table

Revision ID: b6dff5751433
Revises: a3b825827cd5
Create Date: 2020-02-04 14:10:49.954415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6dff5751433'
down_revision = 'a3b825827cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('root', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_author'), 'poem', ['author'], unique=False)
    op.create_index(op.f('ix_poem_title'), 'poem', ['title'], unique=False)
    op.drop_index('ix_poem_data_author', table_name='poem_data')
    op.drop_index('ix_poem_data_title', table_name='poem_data')
    op.drop_table('poem_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('root', sa.VARCHAR(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_poem_data_title', 'poem_data', ['title'], unique=False)
    op.create_index('ix_poem_data_author', 'poem_data', ['author'], unique=False)
    op.drop_index(op.f('ix_poem_title'), table_name='poem')
    op.drop_index(op.f('ix_poem_author'), table_name='poem')
    op.drop_table('poem')
    # ### end Alembic commands ###
