"""empty message

Revision ID: d0e376c69925
Revises: b8896e508db0
Create Date: 2020-02-10 22:44:16.368191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e376c69925'
down_revision = 'b8896e508db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poem', 'timestamp')
    # ### end Alembic commands ###
